// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.roo.test.domain;

import com.roo.test.domain.ApplicationConversionServiceFactoryBean;
import com.roo.test.domain.Gold;
import org.springframework.beans.factory.annotation.Configurable;
import org.springframework.core.convert.converter.Converter;
import org.springframework.format.FormatterRegistry;

privileged aspect ApplicationConversionServiceFactoryBean_Roo_ConversionService {
    
    declare @type: ApplicationConversionServiceFactoryBean: @Configurable;
    
    public Converter<Gold, String> ApplicationConversionServiceFactoryBean.getGoldToStringConverter() {
        return new org.springframework.core.convert.converter.Converter<com.roo.test.domain.Gold, java.lang.String>() {
            public String convert(Gold gold) {
                return new StringBuilder().append(gold.getName()).toString();
            }
        };
    }
    
    public Converter<Long, Gold> ApplicationConversionServiceFactoryBean.getIdToGoldConverter() {
        return new org.springframework.core.convert.converter.Converter<java.lang.Long, com.roo.test.domain.Gold>() {
            public com.roo.test.domain.Gold convert(java.lang.Long id) {
                return Gold.findGold(id);
            }
        };
    }
    
    public Converter<String, Gold> ApplicationConversionServiceFactoryBean.getStringToGoldConverter() {
        return new org.springframework.core.convert.converter.Converter<java.lang.String, com.roo.test.domain.Gold>() {
            public com.roo.test.domain.Gold convert(String id) {
                return getObject().convert(getObject().convert(id, Long.class), Gold.class);
            }
        };
    }
    
    public void ApplicationConversionServiceFactoryBean.installLabelConverters(FormatterRegistry registry) {
        registry.addConverter(getGoldToStringConverter());
        registry.addConverter(getIdToGoldConverter());
        registry.addConverter(getStringToGoldConverter());
    }
    
    public void ApplicationConversionServiceFactoryBean.afterPropertiesSet() {
        super.afterPropertiesSet();
        installLabelConverters(getObject());
    }
    
}
