// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.roo.test.domain;

import com.roo.test.domain.Gold;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect Gold_Roo_Configurable {
    
    declare @type: Gold: @Configurable;
    
}
