// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.roo.test.domain;

import com.roo.test.domain.Gold;
import java.util.List;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import org.springframework.transaction.annotation.Transactional;

privileged aspect Gold_Roo_Jpa_ActiveRecord {
    
    @PersistenceContext
    transient EntityManager Gold.entityManager;
    
    public static final List<String> Gold.fieldNames4OrderClauseFilter = java.util.Arrays.asList("Name");
    
    public static final EntityManager Gold.entityManager() {
        EntityManager em = new Gold().entityManager;
        if (em == null) throw new IllegalStateException("Entity manager has not been injected (is the Spring Aspects JAR configured as an AJC/AJDT aspects library?)");
        return em;
    }
    
    public static long Gold.countGolds() {
        return entityManager().createQuery("SELECT COUNT(o) FROM Gold o", Long.class).getSingleResult();
    }
    
    public static List<Gold> Gold.findAllGolds() {
        return entityManager().createQuery("SELECT o FROM Gold o", Gold.class).getResultList();
    }
    
    public static List<Gold> Gold.findAllGolds(String sortFieldName, String sortOrder) {
        String jpaQuery = "SELECT o FROM Gold o";
        if (fieldNames4OrderClauseFilter.contains(sortFieldName)) {
            jpaQuery = jpaQuery + " ORDER BY " + sortFieldName;
            if ("ASC".equalsIgnoreCase(sortOrder) || "DESC".equalsIgnoreCase(sortOrder)) {
                jpaQuery = jpaQuery + " " + sortOrder;
            }
        }
        return entityManager().createQuery(jpaQuery, Gold.class).getResultList();
    }
    
    public static Gold Gold.findGold(Long id) {
        if (id == null) return null;
        return entityManager().find(Gold.class, id);
    }
    
    public static List<Gold> Gold.findGoldEntries(int firstResult, int maxResults) {
        return entityManager().createQuery("SELECT o FROM Gold o", Gold.class).setFirstResult(firstResult).setMaxResults(maxResults).getResultList();
    }
    
    public static List<Gold> Gold.findGoldEntries(int firstResult, int maxResults, String sortFieldName, String sortOrder) {
        String jpaQuery = "SELECT o FROM Gold o";
        if (fieldNames4OrderClauseFilter.contains(sortFieldName)) {
            jpaQuery = jpaQuery + " ORDER BY " + sortFieldName;
            if ("ASC".equalsIgnoreCase(sortOrder) || "DESC".equalsIgnoreCase(sortOrder)) {
                jpaQuery = jpaQuery + " " + sortOrder;
            }
        }
        return entityManager().createQuery(jpaQuery, Gold.class).setFirstResult(firstResult).setMaxResults(maxResults).getResultList();
    }
    
    @Transactional
    public void Gold.persist() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.persist(this);
    }
    
    @Transactional
    public void Gold.remove() {
        if (this.entityManager == null) this.entityManager = entityManager();
        if (this.entityManager.contains(this)) {
            this.entityManager.remove(this);
        } else {
            Gold attached = Gold.findGold(this.id);
            this.entityManager.remove(attached);
        }
    }
    
    @Transactional
    public void Gold.flush() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.flush();
    }
    
    @Transactional
    public void Gold.clear() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.clear();
    }
    
    @Transactional
    public Gold Gold.merge() {
        if (this.entityManager == null) this.entityManager = entityManager();
        Gold merged = this.entityManager.merge(this);
        this.entityManager.flush();
        return merged;
    }
    
}
