// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.roo.test.domain;

import com.roo.test.domain.Gold;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Version;

privileged aspect Gold_Roo_Jpa_Entity {
    
    declare @type: Gold: @Entity;
    
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @Column(name = "id")
    private Long Gold.id;
    
    @Version
    @Column(name = "version")
    private Integer Gold.version;
    
    public Long Gold.getId() {
        return this.id;
    }
    
    public void Gold.setId(Long id) {
        this.id = id;
    }
    
    public Integer Gold.getVersion() {
        return this.version;
    }
    
    public void Gold.setVersion(Integer version) {
        this.version = version;
    }
    
}
